spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
  datasource:
    password: root123
    url: jdbc:postgresql://localhost:5432/bozor
    username: postgres
    driver-class-name: org.postgresql.Driver
  jackson:
    serialization:
      fail-on-empty-beans: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    jwt:
      secret-key: 0498EA6C131119796421B127771D6B400EF8D151283A8785234D29AFA6F575BE
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
application:
  minio:
    applicationName: bozor
    host: http://localhost:9000
    username: rootbozor
    password: rootbozor
server:
  port: 8888

logging:
  file:
    name: bozor-application.log

